
POST http://localhost:8080/create-developers
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 10,
  "memberId": "mmm",
  "name": "mmm",
  "age": 20
}